// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAtp2btdSBMD2ApJ34cfBznMe2xpB3xiU',
    appId: '1:1031378357241:web:4b82a719ad3cd79d144b28',
    messagingSenderId: '1031378357241',
    projectId: 'automates-b8329',
    authDomain: 'automates-b8329.firebaseapp.com',
    storageBucket: 'automates-b8329.appspot.com',
    measurementId: 'G-P84SFJMCDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0AF7FLf6Ifdy-LczAiqyJimcXWB-LlyU',
    appId: '1:1031378357241:android:cd1318df74958b14144b28',
    messagingSenderId: '1031378357241',
    projectId: 'automates-b8329',
    storageBucket: 'automates-b8329.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWPw8SY6SBJjr4CJmWnQ68gDjTU72atsA',
    appId: '1:1031378357241:ios:bf37ae6239c66e3f144b28',
    messagingSenderId: '1031378357241',
    projectId: 'automates-b8329',
    storageBucket: 'automates-b8329.appspot.com',
    iosBundleId: 'com.example.automates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWPw8SY6SBJjr4CJmWnQ68gDjTU72atsA',
    appId: '1:1031378357241:ios:3087fea05c204c61144b28',
    messagingSenderId: '1031378357241',
    projectId: 'automates-b8329',
    storageBucket: 'automates-b8329.appspot.com',
    iosBundleId: 'com.example.automates.RunnerTests',
  );
}
